services:
  db:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: omop
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "omop"]
      interval: 5s
      timeout: 5s
      retries: 5

  omop-lite:
    image: ghcr.io/health-informatics-uon/omop-lite:sha-c6054ef
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PASSWORD: postgres
      DB_NAME: omop
      SYNTHETIC: true
      SYNTHETIC_NUMBER: 1000

  analytics-dev: 
    build:
      context: ../../
      dockerfile: docker/analytics-dev/Dockerfile
    command:
      - "--user-query"
      - "SELECT value_as_number FROM measurement WHERE measurement_concept_id = 43055141 AND value_as_number IS NOT NULL"
      - "--analysis"
      - "mean"
      - "--output-filename"
      - "/tmp/output/output"
      - "--output-format"
      - "json"
    volumes:
      - ./test-output:/tmp/output
    depends_on:
      omop-lite:
        condition: service_completed_successfully
    environment:
      postgresServer: db
      postgresPort: 5432
      postgresSchema: public
      postgresDatabase: omop
      postgresUsername: postgres
      postgresPassword: postgres
